In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
from google.colab import files
uploaded = files.upload()

Saving SuperMarket Analysis.csv to SuperMarket Analysis.csv

In [5]:
df = pd.read_csv("SuperMarket Analysis.csv")
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [7]:
df.describe()

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

In [8]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [9]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.columns

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price', 'quantity', 'tax_5%', 'sales', 'date',
       'time', 'payment', 'cogs', 'gross_margin_percentage', 'gross_income',
       'rating'],
      dtype='object')

In [10]:
df.columns

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price', 'quantity', 'tax_5%', 'sales', 'date',
       'time', 'payment', 'cogs', 'gross_margin_percentage', 'gross_income',
       'rating'],
      dtype='object')

In [11]:
df = df.rename(columns={
    "tax_5%": "tax_5"
})

df.columns

Index(['invoice_id', 'branch', 'city', 'customer_type', 'gender',
       'product_line', 'unit_price', 'quantity', 'tax_5', 'sales', 'date',
       'time', 'payment', 'cogs', 'gross_margin_percentage', 'gross_income',
       'rating'],
      dtype='object')

In [12]:
df_produto = df.groupby("product_line").agg({
    "sales": "sum",
    "cogs": "sum",
    "gross_income": "sum",
    "quantity": "sum"
}).reset_index()

In [13]:
df_produto

             product_line       sales      cogs  gross_income  quantity
0  Electronic accessories  54337.5315  51750.03     2587.5015       971
1     Fashion accessories  54305.8950  51719.90     2585.9950       902
2      Food and beverages  56144.8440  53471.28     2673.5640       952
3       Health and beauty  49193.7390  46851.18     2342.5590       854
4      Home and lifestyle  53861.9130  51297.06     2564.8530       911
5       Sports and travel  55122.8265  52497.93     2624.8965       920

In [14]:
df_produto = df_produto.sort_values(
    by="gross_income",
    ascending=False
)

In [15]:
df_produto["lucro_acumulado"] = df_produto["gross_income"].cumsum()

In [16]:
df_produto["percentual_acumulado"] = (
    df_produto["lucro_acumulado"] /
    df_produto["gross_income"].sum()
)

In [17]:
def classificar_abc(p):
    if p <= 0.70:
        return "A"
    elif p <= 0.90:
        return "B"
    else:
        return "C"

In [18]:
df_produto["classe_abc"] = (
    df_produto["percentual_acumulado"]
    .apply(classificar_abc)
)

In [19]:
df_produto

,product_line,sales,cogs,gross_income,quantity,lucro_acumulado,percentual_acumulado,classe_abc
2,Food and beverages,56144.8440,53471.28,2673.5640,952,2673.5640,0.173841,A
5,Sports and travel,55122.8265,52497.93,2624.8965,920,5298.4605,0.344517,A
0,Electronic accessories,54337.5315,51750.03,2587.5015,971,7885.9620,0.512762,A
1,Fashion accessories,54305.8950,51719.90,2585.9950,902,10471.9570,0.680909,A
4,Home and lifestyle,53861.9130,51297.06,2564.8530,911,13036.8100,0.847682,B
3,Health and beauty,49193.7390,46851.18,2342.5590,854,15379.3690,1.000000,C

In [20]:
df_produto.to_csv("dados_tratados.csv", index=False)

In [21]:
from google.colab import files
files.download("dados_tratados.csv")

In [1]:
df_produto["classe_abc"] = df_produto["classe_abc"].astype(str)

NameError: name 'df_produto' is not defined

In [3]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving SuperMarket Analysis.csv to SuperMarket Analysis.csv

In [5]:
df = pd.read_csv("SuperMarket Analysis.csv")

In [6]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df = df.rename(columns={"tax_5%": "tax_5"})

In [7]:
df_produto = df.groupby("product_line").agg({
    "sales": "sum",
    "cogs": "sum",
    "gross_income": "sum",
    "quantity": "sum"
}).reset_index()

In [8]:
df_produto = df_produto.sort_values(
    by="gross_income",
    ascending=False
)

In [9]:
df_produto["lucro_acumulado"] = df_produto["gross_income"].cumsum()

df_produto["percentual_acumulado"] = (
    df_produto["lucro_acumulado"] /
    df_produto["gross_income"].sum()
)

In [10]:
def classificar_abc(p):
    if p <= 0.70:
        return "A"
    elif p <= 0.90:
        return "B"
    else:
        return "C"

df_produto["classe_abc"] = (
    df_produto["percentual_acumulado"]
    .apply(classificar_abc)
)

In [11]:
df_produto["classe_abc"] = df_produto["classe_abc"].astype(str)

In [12]:
df_produto.to_csv("dados_tratados.csv", index=False)

In [13]:
from google.colab import files
files.download("dados_tratados.csv")

In [14]:
df_produto["diagnostico"] = df_produto["classe_abc"].map({
    "A": "Priorizar",
    "B": "Otimizar",
    "C": "Revisar"
})

In [15]:
df_produto

,product_line,sales,cogs,gross_income,quantity,lucro_acumulado,percentual_acumulado,classe_abc,diagnostico
2,Food and beverages,56144.8440,53471.28,2673.5640,952,2673.5640,0.173841,A,Priorizar
5,Sports and travel,55122.8265,52497.93,2624.8965,920,5298.4605,0.344517,A,Priorizar
0,Electronic accessories,54337.5315,51750.03,2587.5015,971,7885.9620,0.512762,A,Priorizar
1,Fashion accessories,54305.8950,51719.90,2585.9950,902,10471.9570,0.680909,A,Priorizar
4,Home and lifestyle,53861.9130,51297.06,2564.8530,911,13036.8100,0.847682,B,Otimizar
3,Health and beauty,49193.7390,46851.18,2342.5590,854,15379.3690,1.000000,C,Revisar

In [16]:
df_produto.to_csv("dados_tratados.csv", index=False)

In [17]:
from google.colab import files
files.download("dados_tratados.csv")